version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - laravel

  mariadb:
    image : mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: homestead
      MARIADB_USER: homestead
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mariadb
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
